`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 14.07.2026 09:16:07
// Design Name: 
// Module Name: boundary_scan_cell
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module boundary_scan_cell ( 
    input  wire tck,          // Test Clock
    input  wire trst_n,       // Asynchronous active-low Test Reset
    input  wire capture_dr,   // TAP state: CaptureDR (1 cycle pulse)
    input  wire shift_dr,     // TAP state: ShiftDR   (level, held during shift)
    input  wire update_dr,    // TAP state: UpdateDR  (1 cycle pulse)
    input  wire mode_extest,  // 1 = EXTEST (drive PO from update_ff)
                               // 0 = NORMAL / SAMPLE-PRELOAD (PO = PI, transparent)
    input  wire si,           // Scan Serial In  (from previous cell / TDI)
    input  wire pi,           // Parallel In     (functional pin or DUT signal)
    output wire so,           // Scan Serial Out (to next cell / toward TDO)
    output wire po            // Parallel Out    (to DUT or functional pin)
);
 
    reg shift_ff;   // Capture/Shift storage element
    reg update_ff;  // Update (preload) storage element
 
    // -------------------------------------------------------------------
    // Capture / Shift stage
    //   capture_dr and shift_dr are mutually exclusive, generated by the
    //   TAP controller FSM (only one TAP state is active at a time), so
    //   priority between them is not functionally ambiguous.
    // -------------------------------------------------------------------
    always @(posedge tck or negedge trst_n) begin
        if (!trst_n) begin
            shift_ff <= 1'b0;
        end else if (capture_dr) begin
            shift_ff <= pi;          // Sample the current parallel value
        end else if (shift_dr) begin
            shift_ff <= si;          // Shift scan data toward TDO
        end
    end
 
    assign so = shift_ff;
 
    // -------------------------------------------------------------------
    // Update (preload) stage
    //   Loads the update register from the shift register once per
    //   UpdateDR pulse. This value is what EXTEST will drive onto PO.
    // -------------------------------------------------------------------
    always @(posedge tck or negedge trst_n) begin
        if (!trst_n) begin
            update_ff <= 1'b0;
        end else if (update_dr) begin
            update_ff <= shift_ff;
        end
    end
 
    // -------------------------------------------------------------------
    // Output mux: EXTEST drives PO from the update register (test control),
    // otherwise the cell is fully transparent (functional / SAMPLE mode).
    // -------------------------------------------------------------------
    assign po = mode_extest ? update_ff : pi;
 
endmodule
