/* Generated by Yosys 0.67+24 (git sha1 0e82bbefe, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* dynports =  1  *)
(* hdlname = "boundary_scan_register" *)
(* src = "boundary_scan_register.v:23.1-61.14" *)
module \$paramod\boundary_scan_register\NUM_CELLS=s32'00000000000000000000000000010000 (tck, trst_n, capture_dr, shift_dr, update_dr, mode_extest, tdi, tdo, pi, po);
  (* src = "boundary_scan_register.v:26.34-26.37" *)
  input tck;
  wire tck;
  (* src = "boundary_scan_register.v:27.34-27.40" *)
  input trst_n;
  wire trst_n;
  (* src = "boundary_scan_register.v:28.34-28.44" *)
  input capture_dr;
  wire capture_dr;
  (* src = "boundary_scan_register.v:29.34-29.42" *)
  input shift_dr;
  wire shift_dr;
  (* src = "boundary_scan_register.v:30.34-30.43" *)
  input update_dr;
  wire update_dr;
  (* src = "boundary_scan_register.v:31.34-31.45" *)
  input mode_extest;
  wire mode_extest;
  (* src = "boundary_scan_register.v:32.34-32.37" *)
  input tdi;
  wire tdi;
  (* src = "boundary_scan_register.v:33.34-33.37" *)
  output tdo;
  wire tdo;
  (* src = "boundary_scan_register.v:34.34-34.36" *)
  input [15:0] pi;
  wire [15:0] pi;
  (* src = "boundary_scan_register.v:35.34-35.36" *)
  output [15:0] po;
  wire [15:0] po;
  (* src = "boundary_scan_register.v:39.24-39.33" *)
  wire [16:0] scan_link;
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[0].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[0]),
    .po(po[0]),
    .shift_dr(shift_dr),
    .si(tdi),
    .so(scan_link[1]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[10].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[10]),
    .po(po[10]),
    .shift_dr(shift_dr),
    .si(scan_link[10]),
    .so(scan_link[11]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[11].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[11]),
    .po(po[11]),
    .shift_dr(shift_dr),
    .si(scan_link[11]),
    .so(scan_link[12]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[12].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[12]),
    .po(po[12]),
    .shift_dr(shift_dr),
    .si(scan_link[12]),
    .so(scan_link[13]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[13].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[13]),
    .po(po[13]),
    .shift_dr(shift_dr),
    .si(scan_link[13]),
    .so(scan_link[14]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[14].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[14]),
    .po(po[14]),
    .shift_dr(shift_dr),
    .si(scan_link[14]),
    .so(scan_link[15]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[15].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[15]),
    .po(po[15]),
    .shift_dr(shift_dr),
    .si(scan_link[15]),
    .so(tdo),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[1].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[1]),
    .po(po[1]),
    .shift_dr(shift_dr),
    .si(scan_link[1]),
    .so(scan_link[2]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[2].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[2]),
    .po(po[2]),
    .shift_dr(shift_dr),
    .si(scan_link[2]),
    .so(scan_link[3]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[3].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[3]),
    .po(po[3]),
    .shift_dr(shift_dr),
    .si(scan_link[3]),
    .so(scan_link[4]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[4].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[4]),
    .po(po[4]),
    .shift_dr(shift_dr),
    .si(scan_link[4]),
    .so(scan_link[5]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[5].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[5]),
    .po(po[5]),
    .shift_dr(shift_dr),
    .si(scan_link[5]),
    .so(scan_link[6]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[6].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[6]),
    .po(po[6]),
    .shift_dr(shift_dr),
    .si(scan_link[6]),
    .so(scan_link[7]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[7].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[7]),
    .po(po[7]),
    .shift_dr(shift_dr),
    .si(scan_link[7]),
    .so(scan_link[8]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[8].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[8]),
    .po(po[8]),
    .shift_dr(shift_dr),
    .si(scan_link[8]),
    .so(scan_link[9]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "boundary_scan_register.v:47.32-58.14" *)
  boundary_scan_cell \bsc_chain[9].u_bsc  (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi(pi[9]),
    .po(po[9]),
    .shift_dr(shift_dr),
    .si(scan_link[9]),
    .so(scan_link[10]),
    .tck(tck),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  assign { scan_link[16], scan_link[0] } = { tdo, tdi };
endmodule

(* dynports =  1  *)
(* hdlname = "instruction_decoder" *)
(* src = "instruction_decoder.v:23.1-43.10" *)
module \$paramod\instruction_decoder\IR_WIDTH=s32'00000000000000000000000000000011 (ir_out, mode_extest, sample_preload_sel, bypass_sel);
  (* src = "instruction_decoder.v:26.32-26.38" *)
  input [2:0] ir_out;
  wire [2:0] ir_out;
  (* src = "instruction_decoder.v:28.32-28.43" *)
  output mode_extest;
  wire mode_extest;
  (* src = "instruction_decoder.v:29.32-29.50" *)
  output sample_preload_sel;
  wire sample_preload_sel;
  (* src = "instruction_decoder.v:30.32-30.42" *)
  output bypass_sel;
  wire bypass_sel;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "instruction_decoder.v:41.35-41.67" *)
  wire _05_;
  assign _00_ = ~ir_out[0];
  assign _05_ = mode_extest |(* src = "instruction_decoder.v:41.35-41.67" *)  sample_preload_sel;
  assign _01_ = _00_ |(* src = "instruction_decoder.v:38.34-38.58" *)  ir_out[1];
  assign _04_ = _01_ |(* src = "instruction_decoder.v:38.34-38.58" *)  ir_out[2];
  assign _02_ = ir_out[0] |(* src = "instruction_decoder.v:37.34-37.50" *)  ir_out[1];
  assign _03_ = _02_ |(* src = "instruction_decoder.v:37.34-37.50" *)  ir_out[2];
  assign mode_extest = ~(* src = "instruction_decoder.v:37.34-37.50" *) _03_;
  assign sample_preload_sel = ~(* src = "instruction_decoder.v:38.34-38.58" *) _04_;
  assign bypass_sel = ~(* src = "instruction_decoder.v:41.33-41.68" *) _05_;
endmodule

(* dynports =  1  *)
(* hdlname = "instruction_register" *)
(* src = "instruction_register.v:23.1-68.10" *)
module \$paramod\instruction_register\IR_WIDTH=s32'00000000000000000000000000000011 (tck, trst_n, capture_ir, shift_ir, update_ir, tdi, tdo, ir_out);
  (* src = "instruction_register.v:26.34-26.37" *)
  input tck;
  wire tck;
  (* src = "instruction_register.v:27.34-27.40" *)
  input trst_n;
  wire trst_n;
  (* src = "instruction_register.v:28.34-28.44" *)
  input capture_ir;
  wire capture_ir;
  (* src = "instruction_register.v:29.34-29.42" *)
  input shift_ir;
  wire shift_ir;
  (* src = "instruction_register.v:30.34-30.43" *)
  input update_ir;
  wire update_ir;
  (* src = "instruction_register.v:31.34-31.37" *)
  input tdi;
  wire tdi;
  (* src = "instruction_register.v:32.34-32.37" *)
  output tdo;
  wire tdo;
  (* src = "instruction_register.v:33.34-33.40" *)
  output [2:0] ir_out;
  reg [2:0] ir_out;
  (* src = "instruction_register.v:44.5-53.8" *)
  wire [2:0] _00_;
  wire _01_;
  wire [2:0] _02_;
  (* src = "instruction_register.v:39.24-39.32" *)
  reg [2:0] ir_shift;
  (* src = "instruction_register.v:44.5-53.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_shift[0] <= 1'h1;
    else if (_01_) ir_shift[0] <= _00_[0];
  (* src = "instruction_register.v:44.5-53.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_shift[1] <= 1'h1;
    else if (_01_) ir_shift[1] <= _00_[1];
  (* src = "instruction_register.v:44.5-53.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_shift[2] <= 1'h1;
    else if (_01_) ir_shift[2] <= _00_[2];
  (* src = "instruction_register.v:60.5-66.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_out[0] <= 1'h1;
    else if (update_ir) ir_out[0] <= ir_shift[0];
  (* src = "instruction_register.v:60.5-66.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_out[1] <= 1'h1;
    else if (update_ir) ir_out[1] <= ir_shift[1];
  (* src = "instruction_register.v:60.5-66.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_out[2] <= 1'h1;
    else if (update_ir) ir_out[2] <= ir_shift[2];
  assign _01_ = capture_ir | shift_ir;
  assign _02_[0] = shift_ir ? (* src = "instruction_register.v:49.22-49.30|instruction_register.v:49.18-52.12" *) ir_shift[1] : 1'hx;
  assign _02_[1] = shift_ir ? (* src = "instruction_register.v:49.22-49.30|instruction_register.v:49.18-52.12" *) ir_shift[2] : 1'hx;
  assign _02_[2] = shift_ir ? (* src = "instruction_register.v:49.22-49.30|instruction_register.v:49.18-52.12" *) tdi : 1'hx;
  assign _00_[0] = capture_ir ? (* src = "instruction_register.v:47.22-47.32|instruction_register.v:47.18-52.12" *) 1'h1 : _02_[0];
  assign _00_[1] = capture_ir ? (* src = "instruction_register.v:47.22-47.32|instruction_register.v:47.18-52.12" *) 1'h0 : _02_[1];
  assign _00_[2] = capture_ir ? (* src = "instruction_register.v:47.22-47.32|instruction_register.v:47.18-52.12" *) 1'h0 : _02_[2];
  assign tdo = ir_shift[0];
endmodule

(* dynports =  1  *)
(* hdlname = "multiplier_4x4" *)
(* src = "multiplier_4x4.v:23.1-37.10" *)
module \$paramod\multiplier_4x4\WIDTH=s32'00000000000000000000000000000100 (a, b, product);
  (* src = "multiplier_4x4.v:26.31-26.32" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "multiplier_4x4.v:27.31-27.32" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "multiplier_4x4.v:28.31-28.38" *)
  output [7:0] product;
  wire [7:0] product;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:198.20-198.21" *)
  wire [7:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:198.23-198.24" *)
  wire [7:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:198.26-198.27" *)
  wire [7:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:200.24-200.25" *)
  wire [7:0] _04_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:203.19-203.21" *)
  wire [7:0] _05_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:203.23-203.25" *)
  wire [7:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:203.27-203.29" *)
  wire [7:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:198.26-198.27" *)
  wire [7:0] _08_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:200.24-200.25" *)
  wire [7:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:203.19-203.21" *)
  wire [7:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:203.23-203.25" *)
  wire [7:0] _12_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:203.27-203.29" *)
  wire [7:0] _13_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _14_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _15_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _16_;
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:240.19-240.41" *)
  wire _17_;
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:240.19-240.41" *)
  wire _18_;
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:241.12-241.34" *)
  wire _19_;
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.19-248.41" *)
  wire _20_;
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.19-248.41" *)
  wire _21_;
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.19-248.41" *)
  wire _22_;
  (* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:240.12-240.41" *)
  wire _23_;
  assign _00_[3] = a[0] & b[3];
  assign _00_[4] = a[1] & b[3];
  assign _00_[5] = a[2] & b[3];
  assign _00_[6] = a[3] & b[3];
  assign _01_[2] = a[0] & b[2];
  assign _01_[3] = a[1] & b[2];
  assign _01_[4] = a[2] & b[2];
  assign _01_[5] = a[3] & b[2];
  assign _02_[1] = a[0] & b[1];
  assign _02_[2] = a[1] & b[1];
  assign _02_[3] = a[2] & b[1];
  assign _02_[4] = a[3] & b[1];
  assign product[0] = a[0] & b[0];
  assign _08_[1] = a[1] & b[0];
  assign _08_[2] = a[2] & b[0];
  assign _08_[3] = a[3] & b[0];
  assign _03_[3] = _06_[3] |(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.25-206.32" *)  _07_[3];
  assign _03_[4] = _06_[4] |(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.25-206.32" *)  _07_[4];
  assign _04_[2] = _01_[2] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.13-206.19" *)  _02_[2];
  assign _04_[3] = _05_[3] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.13-206.19" *)  _02_[3];
  assign _04_[4] = _05_[4] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.13-206.19" *)  _02_[4];
  assign _03_[2] = _02_[2] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.38-205.44" *)  _01_[2];
  assign _07_[3] = _02_[3] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.38-205.44" *)  _05_[3];
  assign _07_[4] = _02_[4] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.38-205.44" *)  _05_[4];
  assign _06_[3] = _00_[3] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _01_[3];
  assign _06_[4] = _00_[4] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _01_[4];
  assign _03_[5] = _00_[5] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _01_[5];
  assign _05_[3] = _00_[3] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _01_[3];
  assign _05_[4] = _00_[4] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _01_[4];
  assign _04_[5] = _00_[5] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _01_[5];
  assign _09_[3] = _12_[3] |(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.25-206.32" *)  _13_[3];
  assign product[1] = _02_[1] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.13-206.19" *)  _08_[1];
  assign _10_[2] = _04_[2] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.13-206.19" *)  _08_[2];
  assign _10_[3] = _11_[3] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:206.13-206.19" *)  _08_[3];
  assign _09_[1] = _08_[1] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.38-205.44" *)  _02_[1];
  assign _09_[2] = _08_[2] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.38-205.44" *)  _04_[2];
  assign _13_[3] = _08_[3] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.38-205.44" *)  _11_[3];
  assign _12_[3] = _04_[3] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _03_[2];
  assign _09_[4] = _04_[4] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _03_[3];
  assign _09_[5] = _04_[5] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _03_[4];
  assign _09_[6] = _00_[6] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _03_[5];
  assign _11_[3] = _04_[3] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _03_[2];
  assign _10_[4] = _04_[4] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _03_[3];
  assign _10_[5] = _04_[5] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _03_[4];
  assign _10_[6] = _00_[6] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _03_[5];
  assign product[3] = _15_[3] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:296.13-296.25" *)  _14_[2];
  assign product[4] = _15_[4] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:296.13-296.25" *)  _14_[3];
  assign product[5] = _15_[5] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:296.13-296.25" *)  _14_[4];
  assign product[6] = _15_[6] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:296.13-296.25" *)  _14_[5];
  assign product[7] = _09_[6] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:296.13-296.25" *)  _14_[6];
  assign _14_[2] = _10_[2] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _09_[1];
  assign _16_[3] = _10_[3] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _09_[2];
  assign _16_[4] = _10_[4] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _09_[3];
  assign _16_[5] = _10_[5] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _09_[4];
  assign _16_[6] = _10_[6] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.26-205.31" *)  _09_[5];
  assign product[2] = _10_[2] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _09_[1];
  assign _15_[3] = _10_[3] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _09_[2];
  assign _15_[4] = _10_[4] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _09_[3];
  assign _15_[5] = _10_[5] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _09_[4];
  assign _15_[6] = _10_[6] ^(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:292.26-292.70|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:205.14-205.19" *)  _09_[5];
  assign _21_ = _15_[4] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.19-248.41" *)  _14_[3];
  assign _14_[5] = _23_ |(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.12-248.41" *)  _20_;
  assign _20_ = _19_ &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.19-248.41" *)  _14_[3];
  assign _22_ = _15_[6] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.19-248.41" *)  _14_[5];
  assign _14_[6] = _16_[6] |(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.12-248.41" *)  _22_;
  assign _19_ = _15_[5] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:241.12-241.34" *)  _15_[4];
  assign _23_ = _16_[5] |(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:240.12-240.41" *)  _18_;
  assign _18_ = _15_[5] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:240.19-240.41" *)  _16_[4];
  assign _14_[3] = _16_[3] |(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:240.12-240.41" *)  _17_;
  assign _17_ = _15_[3] &(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:240.19-240.41" *)  _14_[2];
  assign _14_[4] = _16_[4] |(* src = "C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\Users\\sneha\\DOWNLO~1\\YOSYS\\OSS-CA~1\\bin\\../share/yosys/techmap.v:248.12-248.41" *)  _21_;
  assign { _03_[7:6], _03_[1:0] } = 4'h0;
  assign { _04_[7:6], _04_[1:0] } = { 1'h0, _00_[6], _02_[1], 1'h0 };
  assign { _05_[7:5], _05_[2:0] } = { 1'h0, _00_[6], _04_[5], _01_[2], 2'h0 };
  assign { _06_[7:5], _06_[2:0] } = { 2'h0, _03_[5], 3'h0 };
  assign { _07_[7:5], _07_[2:0] } = { 3'h0, _03_[2], 2'h0 };
  assign { _16_[7], _16_[2:0] } = { 1'h0, _14_[2], 2'h0 };
  assign { _08_[7:4], _08_[0] } = { 4'h0, product[0] };
  assign { _09_[7], _09_[0] } = 2'h0;
  assign { _10_[7], _10_[1:0] } = { 1'h0, product[1:0] };
  assign { _11_[7:4], _11_[2:0] } = { 1'h0, _10_[6:4], _04_[2], _02_[1], 1'h0 };
  assign { _12_[7:4], _12_[2:0] } = { 1'h0, _09_[6:4], 3'h0 };
  assign { _13_[7:4], _13_[2:0] } = { 4'h0, _09_[2:1], 1'h0 };
  assign _14_[1:0] = 2'h0;
  assign { _15_[7], _15_[2:0] } = { _09_[6], product[2:0] };
  assign { _00_[7], _00_[2:0] } = 4'h0;
  assign { _01_[7:6], _01_[1:0] } = 4'h0;
  assign { _02_[7:5], _02_[0] } = 4'h0;
endmodule

(* src = "boundary_scan_cell.v:23.1-77.10" *)
module boundary_scan_cell(tck, trst_n, capture_dr, shift_dr, update_dr, mode_extest, si, pi, so, po);
  (* src = "boundary_scan_cell.v:24.17-24.20" *)
  input tck;
  wire tck;
  (* src = "boundary_scan_cell.v:25.17-25.23" *)
  input trst_n;
  wire trst_n;
  (* src = "boundary_scan_cell.v:26.17-26.27" *)
  input capture_dr;
  wire capture_dr;
  (* src = "boundary_scan_cell.v:27.17-27.25" *)
  input shift_dr;
  wire shift_dr;
  (* src = "boundary_scan_cell.v:28.17-28.26" *)
  input update_dr;
  wire update_dr;
  (* src = "boundary_scan_cell.v:29.17-29.28" *)
  input mode_extest;
  wire mode_extest;
  (* src = "boundary_scan_cell.v:31.17-31.19" *)
  input si;
  wire si;
  (* src = "boundary_scan_cell.v:32.17-32.19" *)
  input pi;
  wire pi;
  (* src = "boundary_scan_cell.v:33.17-33.19" *)
  output so;
  wire so;
  (* src = "boundary_scan_cell.v:34.17-34.19" *)
  output po;
  wire po;
  (* src = "boundary_scan_cell.v:46.5-54.8" *)
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "boundary_scan_cell.v:37.9-37.17" *)
  reg shift_ff;
  (* src = "boundary_scan_cell.v:38.9-38.18" *)
  reg update_ff;
  (* src = "boundary_scan_cell.v:46.5-54.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) shift_ff <= 1'h0;
    else if (_1_) shift_ff <= _0_;
  (* src = "boundary_scan_cell.v:63.5-69.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) update_ff <= 1'h0;
    else if (update_dr) update_ff <= shift_ff;
  assign _1_ = capture_dr | shift_dr;
  assign po = mode_extest ? (* src = "boundary_scan_cell.v:75.17-75.45" *) update_ff : pi;
  assign _2_ = shift_dr ? (* src = "boundary_scan_cell.v:51.22-51.30|boundary_scan_cell.v:51.18-53.12" *) si : 1'hx;
  assign _0_ = capture_dr ? (* src = "boundary_scan_cell.v:49.22-49.32|boundary_scan_cell.v:49.18-53.12" *) pi : _2_;
  assign so = shift_ff;
endmodule

(* src = "bypass_register.v:23.1-46.10" *)
module bypass_register(tck, trst_n, capture_dr, shift_dr, tdi, tdo);
  (* src = "bypass_register.v:24.17-24.20" *)
  input tck;
  wire tck;
  (* src = "bypass_register.v:25.17-25.23" *)
  input trst_n;
  wire trst_n;
  (* src = "bypass_register.v:26.17-26.27" *)
  input capture_dr;
  wire capture_dr;
  (* src = "bypass_register.v:27.17-27.25" *)
  input shift_dr;
  wire shift_dr;
  (* src = "bypass_register.v:28.17-28.20" *)
  input tdi;
  wire tdi;
  (* src = "bypass_register.v:29.17-29.20" *)
  output tdo;
  wire tdo;
  (* src = "bypass_register.v:34.5-42.8" *)
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "bypass_register.v:32.9-32.18" *)
  reg bypass_ff;
  (* src = "bypass_register.v:34.5-42.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) bypass_ff <= 1'h0;
    else if (_1_) bypass_ff <= _0_;
  assign _1_ = capture_dr | shift_dr;
  assign _2_ = shift_dr ? (* src = "bypass_register.v:39.22-39.30|bypass_register.v:39.18-41.12" *) tdi : 1'hx;
  assign _0_ = capture_dr ? (* src = "bypass_register.v:37.22-37.32|bypass_register.v:37.18-41.12" *) 1'h0 : _2_;
  assign tdo = bypass_ff;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "jtag_top.v:22.1-188.10" *)
module jtag_top(tck, tms, trst_n, tdi, tdo, a_func, b_func, y_func, dbg_tap_state, dbg_ir_out, dbg_mode_extest);
  (* src = "jtag_top.v:28.36-28.39" *)
  input tck;
  wire tck;
  (* src = "jtag_top.v:29.36-29.39" *)
  input tms;
  wire tms;
  (* src = "jtag_top.v:30.36-30.42" *)
  input trst_n;
  wire trst_n;
  (* src = "jtag_top.v:31.36-31.39" *)
  input tdi;
  wire tdi;
  (* src = "jtag_top.v:32.36-32.39" *)
  output tdo;
  wire tdo;
  (* src = "jtag_top.v:35.36-35.42" *)
  input [3:0] a_func;
  wire [3:0] a_func;
  (* src = "jtag_top.v:36.36-36.42" *)
  input [3:0] b_func;
  wire [3:0] b_func;
  (* src = "jtag_top.v:37.36-37.42" *)
  output [7:0] y_func;
  wire [7:0] y_func;
  (* src = "jtag_top.v:40.36-40.49" *)
  output [3:0] dbg_tap_state;
  wire [3:0] dbg_tap_state;
  (* src = "jtag_top.v:41.36-41.46" *)
  output [2:0] dbg_ir_out;
  wire [2:0] dbg_ir_out;
  (* src = "jtag_top.v:42.36-42.51" *)
  output dbg_mode_extest;
  wire dbg_mode_extest;
  (* src = "jtag_top.v:168.24-169.31" *)
  wire _0_;
  (* src = "jtag_top.v:111.30-111.38" *)
  wire [3:0] a_to_dut;
  (* src = "jtag_top.v:112.30-112.38" *)
  wire [3:0] b_to_dut;
  (* src = "jtag_top.v:105.29-105.35" *)
  wire [15:0] bsr_pi;
  (* src = "jtag_top.v:106.29-106.35" *)
  wire [15:0] bsr_po;
  (* src = "jtag_top.v:107.30-107.37" *)
  wire bsr_tdo;
  (* src = "jtag_top.v:93.43-93.53" *)
  wire bypass_sel;
  (* src = "jtag_top.v:149.10-149.20" *)
  wire bypass_tdo;
  (* src = "jtag_top.v:49.16-49.26" *)
  wire capture_dr;
  (* src = "jtag_top.v:50.16-50.26" *)
  wire capture_ir;
  (* src = "jtag_top.v:49.38-49.46" *)
  (* unused_bits = "0" *)
  wire exit1_dr;
  (* src = "jtag_top.v:50.38-50.46" *)
  (* unused_bits = "0" *)
  wire exit1_ir;
  (* src = "jtag_top.v:49.58-49.66" *)
  (* unused_bits = "0" *)
  wire exit2_dr;
  (* src = "jtag_top.v:50.58-50.66" *)
  (* unused_bits = "0" *)
  wire exit2_ir;
  (* src = "jtag_top.v:79.25-79.31" *)
  wire [2:0] ir_out;
  (* src = "jtag_top.v:80.26-80.32" *)
  wire ir_tdo;
  (* src = "jtag_top.v:93.10-93.21" *)
  wire mode_extest;
  (* src = "jtag_top.v:49.48-49.56" *)
  (* unused_bits = "0" *)
  wire pause_dr;
  (* src = "jtag_top.v:50.48-50.56" *)
  (* unused_bits = "0" *)
  wire pause_ir;
  (* src = "jtag_top.v:48.34-48.47" *)
  (* unused_bits = "0" *)
  wire run_test_idle;
  (* src = "jtag_top.v:93.23-93.41" *)
  (* unused_bits = "0" *)
  wire sample_preload_sel;
  (* src = "jtag_top.v:48.49-48.63" *)
  (* unused_bits = "0" *)
  wire select_dr_scan;
  (* src = "jtag_top.v:48.65-48.79" *)
  (* unused_bits = "0" *)
  wire select_ir_scan;
  (* src = "jtag_top.v:49.28-49.36" *)
  wire shift_dr;
  (* src = "jtag_top.v:50.28-50.36" *)
  wire shift_ir;
  (* src = "jtag_top.v:51.16-51.25" *)
  wire [3:0] tap_state;
  (* src = "jtag_top.v:165.10-165.19" *)
  wire tdo_mux_d;
  (* src = "jtag_top.v:171.9-171.16" *)
  reg tdo_reg;
  (* src = "jtag_top.v:48.16-48.32" *)
  (* unused_bits = "0" *)
  wire test_logic_reset;
  (* src = "jtag_top.v:49.68-49.77" *)
  wire update_dr;
  (* src = "jtag_top.v:50.68-50.77" *)
  wire update_ir;
  (* src = "jtag_top.v:113.30-113.40" *)
  wire [7:0] y_from_dut;
  (* src = "jtag_top.v:172.5-177.8" *)
  always @(negedge tck, negedge trst_n)
    if (!trst_n) tdo_reg <= 1'h0;
    else tdo_reg <= tdo_mux_d;
  assign _0_ = bypass_sel ? (* src = "jtag_top.v:168.24-169.31" *) bypass_tdo : bsr_tdo;
  assign tdo_mux_d = shift_ir ? (* src = "jtag_top.v:167.24-169.31" *) ir_tdo : _0_;
  (* src = "jtag_top.v:124.56-135.6" *)
  \$paramod\boundary_scan_register\NUM_CELLS=s32'00000000000000000000000000010000  u_bsr (
    .capture_dr(capture_dr),
    .mode_extest(mode_extest),
    .pi({ y_from_dut, b_func, a_func }),
    .po(bsr_po),
    .shift_dr(shift_dr),
    .tck(tck),
    .tdi(tdi),
    .tdo(bsr_tdo),
    .trst_n(trst_n),
    .update_dr(update_dr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "jtag_top.v:151.21-158.6" *)
  bypass_register u_bypass (
    .capture_dr(capture_dr),
    .shift_dr(shift_dr),
    .tck(tck),
    .tdi(tdi),
    .tdo(bypass_tdo),
    .trst_n(trst_n)
  );
  (* src = "jtag_top.v:95.48-100.6" *)
  \$paramod\instruction_decoder\IR_WIDTH=s32'00000000000000000000000000000011  u_decoder (
    .bypass_sel(bypass_sel),
    .ir_out(ir_out),
    .mode_extest(mode_extest),
    .sample_preload_sel(sample_preload_sel)
  );
  (* src = "jtag_top.v:140.41-144.6" *)
  \$paramod\multiplier_4x4\WIDTH=s32'00000000000000000000000000000100  u_dut (
    .a(bsr_po[3:0]),
    .b(bsr_po[7:4]),
    .product(y_from_dut)
  );
  (* src = "jtag_top.v:82.49-91.6" *)
  \$paramod\instruction_register\IR_WIDTH=s32'00000000000000000000000000000011  u_ir (
    .capture_ir(capture_ir),
    .ir_out(ir_out),
    .shift_ir(shift_ir),
    .tck(tck),
    .tdi(tdi),
    .tdo(ir_tdo),
    .trst_n(trst_n),
    .update_ir(update_ir)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "jtag_top.v:53.20-74.6" *)
  tap_controller u_tap (
    .capture_dr(capture_dr),
    .capture_ir(capture_ir),
    .exit1_dr(exit1_dr),
    .exit1_ir(exit1_ir),
    .exit2_dr(exit2_dr),
    .exit2_ir(exit2_ir),
    .pause_dr(pause_dr),
    .pause_ir(pause_ir),
    .run_test_idle(run_test_idle),
    .select_dr_scan(select_dr_scan),
    .select_ir_scan(select_ir_scan),
    .shift_dr(shift_dr),
    .shift_ir(shift_ir),
    .tap_state(tap_state),
    .tck(tck),
    .test_logic_reset(test_logic_reset),
    .tms(tms),
    .trst_n(trst_n),
    .update_dr(update_dr),
    .update_ir(update_ir)
  );
  assign b_to_dut = bsr_po[7:4];
  assign a_to_dut = bsr_po[3:0];
  assign bsr_pi = { y_from_dut, b_func, a_func };
  assign dbg_mode_extest = mode_extest;
  assign dbg_ir_out = ir_out;
  assign dbg_tap_state = tap_state;
  assign y_func = bsr_po[15:8];
  assign tdo = tdo_reg;
endmodule

(* src = "tap_controller.v:24.1-132.10" *)
module tap_controller(tck, tms, trst_n, tap_state, test_logic_reset, run_test_idle, select_dr_scan, capture_dr, shift_dr, exit1_dr, pause_dr, exit2_dr, update_dr, select_ir_scan, capture_ir, shift_ir, exit1_ir, pause_ir, exit2_ir, update_ir);
  (* src = "tap_controller.v:25.23-25.26" *)
  input tck;
  wire tck;
  (* src = "tap_controller.v:26.23-26.26" *)
  input tms;
  wire tms;
  (* src = "tap_controller.v:27.23-27.29" *)
  input trst_n;
  wire trst_n;
  (* src = "tap_controller.v:29.23-29.32" *)
  output [3:0] tap_state;
  wire [3:0] tap_state;
  (* src = "tap_controller.v:31.23-31.39" *)
  output test_logic_reset;
  wire test_logic_reset;
  (* src = "tap_controller.v:32.23-32.36" *)
  output run_test_idle;
  wire run_test_idle;
  (* src = "tap_controller.v:33.23-33.37" *)
  output select_dr_scan;
  wire select_dr_scan;
  (* src = "tap_controller.v:34.23-34.33" *)
  output capture_dr;
  wire capture_dr;
  (* src = "tap_controller.v:35.23-35.31" *)
  output shift_dr;
  wire shift_dr;
  (* src = "tap_controller.v:36.23-36.31" *)
  output exit1_dr;
  wire exit1_dr;
  (* src = "tap_controller.v:37.23-37.31" *)
  output pause_dr;
  wire pause_dr;
  (* src = "tap_controller.v:38.23-38.31" *)
  output exit2_dr;
  wire exit2_dr;
  (* src = "tap_controller.v:39.23-39.32" *)
  output update_dr;
  wire update_dr;
  (* src = "tap_controller.v:40.23-40.37" *)
  output select_ir_scan;
  wire select_ir_scan;
  (* src = "tap_controller.v:41.23-41.33" *)
  output capture_ir;
  wire capture_ir;
  (* src = "tap_controller.v:42.23-42.31" *)
  output shift_ir;
  wire shift_ir;
  (* src = "tap_controller.v:43.23-43.31" *)
  output exit1_ir;
  wire exit1_ir;
  (* src = "tap_controller.v:44.23-44.31" *)
  output pause_ir;
  wire pause_ir;
  (* src = "tap_controller.v:45.23-45.31" *)
  output exit2_ir;
  wire exit2_ir;
  (* src = "tap_controller.v:46.23-46.32" *)
  output update_ir;
  wire update_ir;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [1:0] _008_;
  wire [1:0] _009_;
  wire [1:0] _010_;
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [5:0] _015_;
  wire [2:0] _016_;
  wire _017_;
  wire _018_;
  wire [5:0] _019_;
  wire [2:0] _020_;
  wire _021_;
  wire _022_;
  wire [5:0] _023_;
  wire [2:0] _024_;
  wire _025_;
  wire _026_;
  wire [5:0] _027_;
  wire [2:0] _028_;
  wire _029_;
  wire _030_;
  wire [5:0] _031_;
  wire [2:0] _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  (* src = "tap_controller.v:100.45-100.78" *)
  wire [3:0] _059_;
  (* src = "tap_controller.v:71.22-71.32" *)
  wire [3:0] next_state;
  (* src = "tap_controller.v:71.15-71.20" *)
  reg [3:0] state;
  (* src = "tap_controller.v:76.5-81.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) state[0] <= 1'h0;
    else state[0] <= next_state[0];
  (* src = "tap_controller.v:76.5-81.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) state[1] <= 1'h0;
    else state[1] <= next_state[1];
  (* src = "tap_controller.v:76.5-81.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) state[2] <= 1'h0;
    else state[2] <= next_state[2];
  (* src = "tap_controller.v:76.5-81.8" *)
  always @(posedge tck, negedge trst_n)
    if (!trst_n) state[3] <= 1'h0;
    else state[3] <= next_state[3];
  assign _003_ = ~state[0];
  assign _005_ = ~state[2];
  assign _004_ = ~state[1];
  assign _006_ = ~state[3];
  assign _007_ = run_test_idle | update_dr;
  assign _002_ = _007_ | update_ir;
  assign _001_ = capture_ir | shift_ir;
  assign _000_ = capture_dr | shift_dr;
  assign _036_ = _008_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _008_[1];
  assign _009_[0] = state[0] |(* src = "tap_controller.v:103.79-103.79|tap_controller.v:87.9-108.16" *)  _004_;
  assign _037_ = _009_[0] |(* src = "tap_controller.v:103.79-103.79|tap_controller.v:87.9-108.16" *)  _008_[1];
  assign _038_ = _010_[0] |(* src = "tap_controller.v:102.79-102.79|tap_controller.v:87.9-108.16" *)  _008_[1];
  assign _008_[1] = _005_ |(* src = "tap_controller.v:101.79-101.79|tap_controller.v:87.9-108.16" *)  _006_;
  assign _039_ = _011_[0] |(* src = "tap_controller.v:101.79-101.79|tap_controller.v:87.9-108.16" *)  _008_[1];
  assign _008_[0] = _003_ |(* src = "tap_controller.v:100.79-100.79|tap_controller.v:87.9-108.16" *)  _004_;
  assign _012_[1] = state[2] |(* src = "tap_controller.v:100.79-100.79|tap_controller.v:87.9-108.16" *)  _006_;
  assign _040_ = _008_[0] |(* src = "tap_controller.v:100.79-100.79|tap_controller.v:87.9-108.16" *)  _012_[1];
  assign _041_ = _009_[0] |(* src = "tap_controller.v:99.81-99.81|tap_controller.v:87.9-108.16" *)  _012_[1];
  assign _042_ = _010_[0] |(* src = "tap_controller.v:97.84-97.84|tap_controller.v:87.9-108.16" *)  _012_[1];
  assign _011_[0] = state[0] |(* src = "tap_controller.v:96.79-96.79|tap_controller.v:87.9-108.16" *)  state[1];
  assign _043_ = _011_[0] |(* src = "tap_controller.v:96.79-96.79|tap_controller.v:87.9-108.16" *)  _012_[1];
  assign _044_ = _008_[0] |(* src = "tap_controller.v:95.79-95.79|tap_controller.v:87.9-108.16" *)  _013_[1];
  assign _013_[1] = _005_ |(* src = "tap_controller.v:94.79-94.79|tap_controller.v:87.9-108.16" *)  state[3];
  assign _045_ = _009_[0] |(* src = "tap_controller.v:94.79-94.79|tap_controller.v:87.9-108.16" *)  _013_[1];
  assign _046_ = _010_[0] |(* src = "tap_controller.v:93.79-93.79|tap_controller.v:87.9-108.16" *)  _013_[1];
  assign _047_ = _011_[0] |(* src = "tap_controller.v:92.79-92.79|tap_controller.v:87.9-108.16" *)  _013_[1];
  assign _014_[1] = state[2] |(* src = "tap_controller.v:91.81-91.81|tap_controller.v:87.9-108.16" *)  state[3];
  assign _048_ = _008_[0] |(* src = "tap_controller.v:91.81-91.81|tap_controller.v:87.9-108.16" *)  _014_[1];
  assign _049_ = _009_[0] |(* src = "tap_controller.v:89.84-89.84|tap_controller.v:87.9-108.16" *)  _014_[1];
  assign _010_[0] = _003_ |(* src = "tap_controller.v:88.84-88.84|tap_controller.v:87.9-108.16" *)  state[1];
  assign _050_ = _010_[0] |(* src = "tap_controller.v:88.84-88.84|tap_controller.v:87.9-108.16" *)  _014_[1];
  assign _015_[0] = test_logic_reset |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  select_dr_scan;
  assign _015_[1] = _000_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit1_dr;
  assign _015_[2] = pause_dr |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit2_dr;
  assign _015_[3] = select_ir_scan |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _001_;
  assign _015_[5] = exit2_ir |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _002_;
  assign _016_[0] = _015_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _015_[1];
  assign _016_[1] = _015_[2] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _015_[3];
  assign _016_[2] = _015_[4] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _015_[5];
  assign _017_ = _016_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _016_[1];
  assign _018_ = _017_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _016_[2];
  assign _019_[0] = _051_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  select_dr_scan;
  assign _019_[4] = exit1_ir |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _052_;
  assign _019_[5] = exit2_ir |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _053_;
  assign _020_[0] = _019_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _019_[1];
  assign _020_[1] = _019_[2] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _019_[3];
  assign _020_[2] = _019_[4] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _019_[5];
  assign _021_ = _020_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _020_[1];
  assign _022_ = _021_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _020_[2];
  assign _023_[3] = _054_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _019_[3];
  assign _023_[4] = _055_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _056_;
  assign _023_[5] = exit2_ir |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _057_;
  assign _024_[0] = _023_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _023_[1];
  assign _024_[1] = pause_dr |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _023_[3];
  assign _024_[2] = _023_[4] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _023_[5];
  assign _025_ = _024_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _024_[1];
  assign _026_ = _025_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _024_[2];
  assign _027_[1] = _000_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _023_[1];
  assign _027_[2] = pause_dr |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _058_;
  assign _028_[1] = _027_[2] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _027_[3];
  assign _028_[2] = _015_[4] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _027_[5];
  assign _029_ = _027_[1] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _028_[1];
  assign _030_ = _029_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _028_[2];
  assign _031_[3] = _054_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _001_;
  assign _015_[4] = exit1_ir |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  pause_ir;
  assign _032_[0] = _031_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _031_[1];
  assign _032_[1] = _031_[2] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _031_[3];
  assign _032_[2] = _015_[4] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit2_ir;
  assign _033_ = _032_[0] |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _032_[1];
  assign _034_ = _033_ |(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _032_[2];
  assign _035_ = _011_[0] |(* src = "tap_controller.v:87.21-87.21|tap_controller.v:87.9-108.16" *)  _014_[1];
  assign update_ir = ~(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *) _036_;
  assign exit2_ir = ~(* src = "tap_controller.v:103.79-103.79|tap_controller.v:87.9-108.16" *) _037_;
  assign pause_ir = ~(* src = "tap_controller.v:102.79-102.79|tap_controller.v:87.9-108.16" *) _038_;
  assign exit1_ir = ~(* src = "tap_controller.v:101.79-101.79|tap_controller.v:87.9-108.16" *) _039_;
  assign shift_ir = ~(* src = "tap_controller.v:100.79-100.79|tap_controller.v:87.9-108.16" *) _040_;
  assign capture_ir = ~(* src = "tap_controller.v:99.81-99.81|tap_controller.v:87.9-108.16" *) _041_;
  assign select_ir_scan = ~(* src = "tap_controller.v:97.84-97.84|tap_controller.v:87.9-108.16" *) _042_;
  assign update_dr = ~(* src = "tap_controller.v:96.79-96.79|tap_controller.v:87.9-108.16" *) _043_;
  assign exit2_dr = ~(* src = "tap_controller.v:95.79-95.79|tap_controller.v:87.9-108.16" *) _044_;
  assign pause_dr = ~(* src = "tap_controller.v:94.79-94.79|tap_controller.v:87.9-108.16" *) _045_;
  assign exit1_dr = ~(* src = "tap_controller.v:93.79-93.79|tap_controller.v:87.9-108.16" *) _046_;
  assign shift_dr = ~(* src = "tap_controller.v:92.79-92.79|tap_controller.v:87.9-108.16" *) _047_;
  assign capture_dr = ~(* src = "tap_controller.v:91.81-91.81|tap_controller.v:87.9-108.16" *) _048_;
  assign select_dr_scan = ~(* src = "tap_controller.v:89.84-89.84|tap_controller.v:87.9-108.16" *) _049_;
  assign run_test_idle = ~(* src = "tap_controller.v:88.84-88.84|tap_controller.v:87.9-108.16" *) _050_;
  assign test_logic_reset = ~(* src = "tap_controller.v:87.21-87.21|tap_controller.v:87.9-108.16" *) _035_;
  assign _059_[0] = ~(* src = "tap_controller.v:105.45-105.83" *) tms;
  assign _051_ = _059_[0] &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  test_logic_reset;
  assign _019_[1] = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _000_;
  assign _019_[2] = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  pause_dr;
  assign _052_ = _059_[0] &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  pause_ir;
  assign _053_ = _059_[0] &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _002_;
  assign _023_[0] = _059_[0] &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  select_dr_scan;
  assign _023_[1] = _059_[0] &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit1_dr;
  assign _054_ = _059_[0] &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  select_ir_scan;
  assign _019_[3] = _059_[0] &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _001_;
  assign _055_ = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit1_ir;
  assign _056_ = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  pause_ir;
  assign _057_ = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _002_;
  assign _058_ = _059_[0] &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit2_dr;
  assign _027_[3] = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  _001_;
  assign _027_[5] = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit2_ir;
  assign _031_[0] = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  select_dr_scan;
  assign _031_[1] = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit1_dr;
  assign _031_[2] = tms &(* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *)  exit2_dr;
  assign next_state[0] = _018_ ? (* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *) _022_ : 1'hx;
  assign next_state[1] = _018_ ? (* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *) _026_ : 1'hx;
  assign next_state[2] = _018_ ? (* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *) _030_ : 1'hx;
  assign next_state[3] = _018_ ? (* src = "tap_controller.v:104.79-104.79|tap_controller.v:87.9-108.16" *) _034_ : 1'hx;
  assign _023_[2] = pause_dr;
  assign _031_[5:4] = { exit2_ir, _015_[4] };
  assign _011_[1] = _008_[1];
  assign _013_[0] = _008_[0];
  assign _010_[1] = _008_[1];
  assign _028_[0] = _027_[1];
  assign { _027_[4], _027_[0] } = { _015_[4], 1'h0 };
  assign _014_[0] = _008_[0];
  assign _012_[0] = _008_[0];
  assign _009_[1] = _008_[1];
  assign _059_[3:1] = { 1'h1, tms, _059_[0] };
  assign tap_state = state;
endmodule
